/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/cabine.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cabine(props) {
  const { nodes, materials } = useGLTF('/models/cabine.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[5.33, 0.458, 0.14]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.041, 0.017, 0.024]}>
        <mesh geometry={nodes.Object001.geometry} material={materials['Golden Teak Wood Texture.002']} position={[0, 22.845, 0]} />
        <mesh geometry={nodes.Object002.geometry} material={materials['Golden Teak Wood Texture']} position={[-14.83, -11.025, 0]} />
        <mesh geometry={nodes.Object003.geometry} material={materials['Golden Teak Wood Texture']} position={[0, -10.566, 0]} />
        <mesh geometry={nodes.Object004.geometry} material={materials['Golden Teak Wood Texture']} position={[0, -13.82, 7.138]} />
        <mesh geometry={nodes.Object005.geometry} material={materials['Material #27']} position={[0, -13.82, 6.532]} />
        <mesh geometry={nodes.Object006.geometry} material={materials['Material #27']} position={[0, -13.82, -8.119]} />
        <mesh geometry={nodes.Object007.geometry} material={materials['Golden Teak Wood Texture']} position={[0, 0.272, 0]} />
        <mesh geometry={nodes.Object008.geometry} material={materials['Golden Teak Wood Texture']} position={[0, -2.982, 7.138]} />
        <mesh geometry={nodes.Object009.geometry} material={materials['Golden Teak Wood Texture']} position={[0, 11.11, 0]} />
        <mesh geometry={nodes.Object010.geometry} material={materials['Golden Teak Wood Texture']} position={[0, 7.856, 7.138]} />
        <mesh geometry={nodes.Object011.geometry} material={materials['Golden Teak Wood Texture']} position={[0, 21.631, 0]} />
        <mesh geometry={nodes.Object012.geometry} material={materials['Golden Teak Wood Texture']} position={[0, 18.694, 7.138]} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials['Wood floor']} position={[7.22, 0.334, -4.16]} />
      <mesh geometry={nodes.Canape.geometry} material={materials.Paper} position={[0.403, 0.463, -1.978]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.MurMilieu.geometry} material={materials.yellow_stone_wall} position={[0.83, 1.25, -2.825]} />
      <mesh geometry={nodes.MurPorteCoulissante.geometry} material={materials.yellow_stone_wall} position={[1.59, 1.25, -4.73]} />
      <mesh geometry={nodes.MurDroit.geometry} material={materials.Paper} position={[5.543, 1.25, -5.075]} />
      <mesh geometry={nodes.MurFond.geometry} material={materials.Paper} position={[0.035, 1.25, -2.54]} />
      <mesh geometry={nodes.MurGauche.geometry} material={materials.Paper} position={[5.54, 1.25, -0.035]} />
      <mesh geometry={nodes.Plafond.geometry} material={nodes.Plafond.material} position={[5.54, 2.5, -2.54]} />
      <group position={[0.104, 1.056, -0.645]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.roundedDoor.geometry} material={materials.Paper} />
        <mesh geometry={nodes.roundedDoor_1.geometry} material={materials['Wood floor']} />
      </group>
      <mesh geometry={nodes.TrouDouche.geometry} material={materials.metal} position={[1.357, 0.072, -4.74]} />
      <mesh geometry={nodes.SupportPommeau.geometry} material={materials.metal} position={[1.52, 1.25, -4.74]} />
      <mesh geometry={nodes.SupportVitre.geometry} material={materials.chrome} position={[1.07, 1.235, -4.37]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Pommeau2.geometry} material={materials.metal} position={[1.15, 1.9, -4.8]} />
      <mesh geometry={nodes.Vitre.geometry} material={materials['Acrylic Glass']} position={[1.07, 1.065, -4.37]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Pommeau1.geometry} material={materials.metal} position={[1.51, 1.45, -4.68]} />
      <mesh geometry={nodes.SolDeDouche.geometry} material={materials.PineWood} position={[0.81, -0.033, -4.73]} scale={[2.068, 2.5, 1.639]} />
      <group position={[2.488, 0.466, -2.283]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[-0.021, -0.02, -0.023]}>
        <mesh geometry={nodes.Mesh355.geometry} material={materials['ceramica_vaso.001']} />
        <mesh geometry={nodes.Mesh355_1.geometry} material={materials.beige_wall_001} />
        <mesh geometry={nodes.Mesh355_2.geometry} material={materials.beige_wall_002} />
        <mesh geometry={nodes.Mesh355_3.geometry} material={materials['Golden Teak Wood Texture']} />
        <mesh geometry={nodes.Mesh355_4.geometry} material={materials.black_matte_a1} />
        <mesh geometry={nodes.Mesh355_5.geometry} material={materials.wood_a1} />
        <mesh geometry={nodes.Mesh355_6.geometry} material={materials.gold_Black_a1} />
        <mesh geometry={nodes.Mesh355_7.geometry} material={materials.leather_10} />
      </group>
      <group position={[4.006, 0.466, -2.283]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[-0.021, -0.02, -0.023]}>
        <mesh geometry={nodes.Mesh402.geometry} material={materials['ceramica_vaso.003']} />
        <mesh geometry={nodes.Mesh402_1.geometry} material={materials['beige_wall_001.003']} />
        <mesh geometry={nodes.Mesh402_2.geometry} material={materials['beige_wall_002.002']} />
        <mesh geometry={nodes.Mesh402_3.geometry} material={materials['Golden Teak Wood Texture.004']} />
        <mesh geometry={nodes.Mesh402_4.geometry} material={materials['black_matte_a1.002']} />
        <mesh geometry={nodes.Mesh402_5.geometry} material={materials['wood_a1.002']} />
        <mesh geometry={nodes.Mesh402_6.geometry} material={materials['gold_Black_a1.002']} />
        <mesh geometry={nodes.Mesh402_7.geometry} material={materials['leather_10.002']} />
      </group>
      <mesh geometry={nodes.faucet_01001.geometry} material={materials['nickel.001']} position={[4.581, 1.076, -5.04]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.faucet_01002.geometry} material={materials['nickel.002']} position={[2.98, 1.076, -5.04]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.furniture.geometry} material={materials['Golden Teak Wood Texture']} position={[3.777, 0.53, -4.553]} />
      <group position={[3.129, 1.064, -5.04]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials.nickel} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials.red} />
        <mesh geometry={nodes.Mesh003_2.geometry} material={materials.blue} />
      </group>
      <group position={[4.741, 1.064, -5.04]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh013.geometry} material={materials['nickel.003']} />
        <mesh geometry={nodes.Mesh013_1.geometry} material={materials['red.003']} />
        <mesh geometry={nodes.Mesh013_2.geometry} material={materials['blue.003']} />
      </group>
      <group position={[4.585, 1.79, -5.04]} rotation={[0, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Mesh004.geometry} material={materials.wood} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={materials['AR3DMat Procedural Realistic Mirror']} />
      </group>
      <group position={[2.995, 1.79, -5.04]} rotation={[0, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Mesh014.geometry} material={materials['wood.001']} />
        <mesh geometry={nodes.Mesh014_1.geometry} material={materials['AR3DMat Procedural Realistic Mirror']} />
      </group>
      <group position={[2.977, 0.9, -4.713]}>
        <mesh geometry={nodes.Mesh009.geometry} material={materials.nickel} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={materials.porcelain} />
      </group>
      <group position={[4.577, 0.9, -4.713]}>
        <mesh geometry={nodes.Mesh005.geometry} material={materials.nickel} />
        <mesh geometry={nodes.Mesh005_1.geometry} material={materials.porcelain} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_0_1.geometry} material={materials['Golden Teak Wood Texture']} />
        <mesh geometry={nodes.mesh_0_2.geometry} material={materials.mesh_group_material_0_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_1_1.geometry} material={materials['Dark Walnut fine wood PBR texture seamless.001']} />
        <mesh geometry={nodes.mesh_1_2.geometry} material={materials.mesh_group_material_1_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_10_1.geometry} material={materials['Dark Walnut fine wood PBR texture seamless.001']} />
        <mesh geometry={nodes.mesh_10_2.geometry} material={materials.mesh_group_material_10_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_11_1.geometry} material={materials['Golden Teak Wood Texture']} />
        <mesh geometry={nodes.mesh_11_2.geometry} material={materials.mesh_group_material_11_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_12_1.geometry} material={materials['Golden Teak Wood Texture']} />
        <mesh geometry={nodes.mesh_12_2.geometry} material={materials.mesh_group_material_12_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_13_1.geometry} material={materials['Golden Teak Wood Texture']} />
        <mesh geometry={nodes.mesh_13_2.geometry} material={materials.mesh_group_material_13_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_14_1.geometry} material={materials['Ancient Burl Chestnut Marbling']} />
        <mesh geometry={nodes.mesh_14_2.geometry} material={materials.mesh_group_material_14_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_2_1.geometry} material={materials['Ancient Burl Chestnut Marbling']} />
        <mesh geometry={nodes.mesh_2_2.geometry} material={materials.mesh_group_material_2_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_3_1.geometry} material={materials['Dark Walnut fine wood PBR texture seamless.001']} />
        <mesh geometry={nodes.mesh_3_2.geometry} material={materials.mesh_group_material_3_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_4_1.geometry} material={materials['Dark cherry fine wood texture']} />
        <mesh geometry={nodes.mesh_4_2.geometry} material={materials.mesh_group_material_4_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_5_1.geometry} material={materials['Dark Walnut fine wood PBR texture seamless.001']} />
        <mesh geometry={nodes.mesh_5_2.geometry} material={materials.mesh_group_material_5_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_6_1.geometry} material={materials.mesh_group_material_6_0} />
        <mesh geometry={nodes.mesh_6_2.geometry} material={materials.mesh_group_material_6_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_7_1.geometry} material={materials.mesh_group_material_7_0} />
        <mesh geometry={nodes.mesh_7_2.geometry} material={materials.mesh_group_material_7_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_8_1.geometry} material={materials['Dark Walnut fine wood PBR texture seamless.001']} />
        <mesh geometry={nodes.mesh_8_2.geometry} material={materials.mesh_group_material_8_1} />
      </group>
      <group position={[0.591, 0.037, -3.056]} rotation={[Math.PI / 2, 0, -3.139]} scale={[0.002, 0.001, 0.001]}>
        <mesh geometry={nodes.mesh_9_1.geometry} material={materials.mesh_group_material_9_0} />
        <mesh geometry={nodes.mesh_9_2.geometry} material={materials.mesh_group_material_9_1} />
      </group>
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.Paper} position={[0.311, 0.246, -3.679]} rotation={[Math.PI / 2, 0, 0]} scale={[0, 0, 0.001]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.Cardboard} position={[0.311, 0.246, -3.679]} rotation={[Math.PI / 2, 0, 0]} scale={[0, 0, 0.001]} />
      <group position={[2.09, 0.846, -4.713]}>
        <mesh geometry={nodes.leaf01001.geometry} material={materials['ceramica_vaso.001']} />
        <mesh geometry={nodes.leaf01001_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.leaf01001_2.geometry} material={materials.ramo} />
        <mesh geometry={nodes.leaf01001_3.geometry} material={materials.terra} />
        <mesh geometry={nodes.leaf01001_4.geometry} material={materials.bocciolo} />
      </group>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material #35']} position={[1.422, 0.045, -3.087]} scale={[0.076, 0.063, 0.076]} />
      <group position={[0.83, 0.045, -3.087]} scale={1.59}>
        <mesh geometry={nodes.Mesh017.geometry} material={materials['vray_Plant 7_terra_001']} />
        <mesh geometry={nodes.Mesh017_1.geometry} material={materials['vray_Plant 7_Sansevieria_plant']} />
      </group>
      <mesh geometry={nodes.Gravel_Baked.geometry} material={materials['Material #39']} position={[1.423, 0.426, -3.09]} scale={1.522} />
      <mesh geometry={nodes.Group_195.geometry} material={materials.Color_A05} position={[8.203, 0.784, -4.851]} rotation={[1.025, -0.7, 1.114]} scale={0.004} />
      <mesh geometry={nodes.Group_194.geometry} material={materials.Color_A05} position={[8.234, 0.839, -4.913]} rotation={[0.377, -0.022, 0.909]} scale={0.004} />
      <mesh geometry={nodes.Group_193.geometry} material={materials.Color_A05} position={[8.204, 0.851, -4.996]} rotation={[-0.278, 0.637, 1.17]} scale={0.004} />
      <mesh geometry={nodes.Group_192.geometry} material={materials.Color_A05} position={[8.136, 0.811, -5.036]} rotation={[-1.503, 0.837, 2.101]} scale={0.004} />
      <mesh geometry={nodes.Group_191.geometry} material={materials.Color_A05} position={[8.08, 0.75, -5.004]} rotation={[-2.406, 0.316, 2.68]} scale={0.004} />
      <mesh geometry={nodes.Group_190.geometry} material={materials.Color_A05} position={[8.079, 0.713, -4.923]} rotation={[-2.976, -0.387, 2.702]} scale={0.004} />
      <mesh geometry={nodes.Group_189.geometry} material={materials.Color_A05} position={[8.208, 0.83, -4.956]} rotation={[-2.066, 0.361, 2.176]} scale={0.004} />
      <mesh geometry={nodes.Group_188.geometry} material={materials.Color_A05} position={[8.119, 0.777, -5.004]} rotation={[1.328, -0.93, 0.847]} scale={0.004} />
      <mesh geometry={nodes.Group_187.geometry} material={materials.Color_A05} position={[8.158, 0.778, -4.961]} rotation={[-2.599, 0.022, 2.469]} scale={0.004} />
      <mesh geometry={nodes.Group_186.geometry} material={materials.Color_A05} position={[8.148, 0.766, -4.954]} rotation={[2.921, -0.771, 2.252]} scale={0.004} />
      <mesh geometry={nodes.Group_185.geometry} material={materials.Color_A05} position={[8.15, 0.761, -4.937]} rotation={[1.279, -0.879, 1.013]} scale={0.004} />
      <mesh geometry={nodes.Group_184.geometry} material={materials.Color_A05} position={[8.163, 0.767, -4.927]} rotation={[0.407, -0.126, 0.638]} scale={0.004} />
      <mesh geometry={nodes.Group_183.geometry} material={materials.Color_A05} position={[8.174, 0.78, -4.935]} rotation={[-0.355, 0.635, 0.952]} scale={0.004} />
      <mesh geometry={nodes.Group_182.geometry} material={materials.Color_A05} position={[8.163, 0.825, -5.018]} rotation={[-3.033, -0.707, 2.244]} scale={0.004} />
      <mesh geometry={nodes.Group_181.geometry} material={materials.Color_A05} position={[8.121, 0.739, -4.932]} rotation={[2.206, -1.068, 1.798]} scale={0.004} />
      <mesh geometry={nodes.Group_180.geometry} material={materials.Color_A05} position={[8.107, 0.723, -4.908]} rotation={[0.862, -0.884, 0.727]} scale={0.004} />
      <mesh geometry={nodes.Group_179.geometry} material={materials.Color_A05} position={[8.111, 0.719, -4.877]} rotation={[0.291, -0.315, 0.484]} scale={0.004} />
      <mesh geometry={nodes.Group_178.geometry} material={materials.Color_A05} position={[8.132, 0.728, -4.854]} rotation={[-0.135, 0.281, 0.575]} scale={0.004} />
      <mesh geometry={nodes.Group_177.geometry} material={materials.Color_A05} position={[8.159, 0.746, -4.852]} rotation={[-0.788, 0.752, 1.014]} scale={0.004} />
      <mesh geometry={nodes.Group_176.geometry} material={materials.Color_A05} position={[8.183, 0.783, -4.915]} rotation={[-0.688, 0.699, 1.152]} scale={0.004} />
      <mesh geometry={nodes.Group_175.geometry} material={materials.Color_A05} position={[8.131, 0.752, -4.943]} rotation={[0.349, -0.039, 0.535]} scale={0.004} />
      <mesh geometry={nodes.Group_174.geometry} material={materials.Color_A05} position={[8.177, 0.764, -4.872]} rotation={[-1.818, 0.776, 1.859]} scale={0.004} />
      <mesh geometry={nodes.Group_173.geometry} material={materials.Color_A05} position={[8.286, 0.918, -4.833]} rotation={[-2.376, 0.185, 1.811]} scale={0.004} />
      <mesh geometry={nodes.Group_172.geometry} material={materials.Color_A05} position={[8.248, 0.968, -5.011]} rotation={[-2.948, -0.535, 1.85]} scale={0.004} />
      <mesh geometry={nodes.Group_171.geometry} material={materials.Color_A05} position={[8.109, 0.902, -5.122]} rotation={[2.189, -1.066, 1.104]} scale={0.004} />
      <mesh geometry={nodes.Group_170.geometry} material={materials.Color_A05} position={[7.978, 0.773, -5.078]} rotation={[0.802, -0.678, 0.101]} scale={0.004} />
      <mesh geometry={nodes.Group_169.geometry} material={materials.Color_A05} position={[7.957, 0.681, -4.914]} rotation={[0.204, 0.04, 0.044]} scale={0.004} />
      <mesh geometry={nodes.Group_168.geometry} material={materials.Color_A05} position={[8.17, 0.77, -4.919]} rotation={[-2.753, 0.001, 2.43]} scale={0.004} />
      <mesh geometry={nodes.Group_167.geometry} material={materials.Color_A05} position={[8.212, 0.812, -4.733]} rotation={[-1.701, 0.676, 1.387]} scale={0.004} />
      <mesh geometry={nodes.Group_166.geometry} material={materials.Color_A05} position={[8.173, 0.815, -4.651]} rotation={[-1.816, 0.79, 1.245]} scale={0.004} />
      <mesh geometry={nodes.Group_165.geometry} material={materials.Color_A05} position={[8.304, 1.016, -4.853]} rotation={[-2.775, -0.086, 1.646]} scale={0.004} />
      <mesh geometry={nodes.Group_164.geometry} material={materials.Color_A05} position={[8.151, 1.01, -5.126]} rotation={[2.388, -0.887, 1.041]} scale={0.004} />
      <mesh geometry={nodes.Group_163.geometry} material={materials.Color_A05} position={[8.063, 0.699, -4.759]} rotation={[-0.525, 0.65, 0.461]} scale={0.004} />
      <mesh geometry={nodes.Group_162.geometry} material={materials.Color_A05} position={[7.914, 0.805, -5.111]} rotation={[0.805, -0.466, -0.099]} scale={0.004} />
      <mesh geometry={nodes.Group_161.geometry} material={materials.Color_A05} position={[7.906, 0.671, -4.827]} rotation={[0, 0.481, -0.08]} scale={0.004} />
      <mesh geometry={nodes.Group_159.geometry} material={materials.Color_G16} position={[7.925, 0.689, -4.776]} rotation={[0, 0.481, -0.08]} scale={0.004} />
      <mesh geometry={nodes.Group_158.geometry} material={materials.Color_A05} position={[8.172, 0.785, -4.951]} rotation={[-1.744, 0.729, 2.019]} scale={0.004} />
      <mesh geometry={nodes.Group_156.geometry} material={materials.Color_A05} position={[8.173, 0.913, -4.751]} rotation={[1.569, -0.563, 1.906]} scale={0.004} />
      <mesh geometry={nodes.Group_155.geometry} material={materials.Color_A05} position={[8.216, 0.982, -4.788]} rotation={[0.556, -0.413, 1.441]} scale={0.004} />
      <mesh geometry={nodes.Group_154.geometry} material={materials.Color_A05} position={[8.232, 0.997, -4.874]} rotation={[-0.263, 0.003, 1.305]} scale={0.004} />
      <mesh geometry={nodes.Group_153.geometry} material={materials.Color_A05} position={[8.21, 0.947, -4.944]} rotation={[-1.097, 0.384, 1.523]} scale={0.004} />
      <mesh geometry={nodes.Group_152.geometry} material={materials.Color_A05} position={[8.167, 0.869, -4.945]} rotation={[-2.082, 0.449, 1.995]} scale={0.004} />
      <mesh geometry={nodes.Group_151.geometry} material={materials.Color_A05} position={[8.134, 0.823, -4.877]} rotation={[-2.967, 0.137, 2.315]} scale={0.004} />
      <mesh geometry={nodes.Group_150.geometry} material={materials.Color_A05} position={[8.22, 0.972, -4.838]} rotation={[-1.785, 0.281, 1.499]} scale={0.004} />
      <mesh geometry={nodes.Group_149.geometry} material={materials.Color_A05} position={[8.19, 0.905, -4.925]} rotation={[1.936, -0.579, 1.616]} scale={0.004} />
      <mesh geometry={nodes.Group_148.geometry} material={materials.Color_A05} position={[8.198, 0.911, -4.867]} rotation={[-2.436, 0.324, 1.887]} scale={0.004} />
      <mesh geometry={nodes.Group_147.geometry} material={materials.Color_A05} position={[8.189, 0.895, -4.866]} rotation={[2.901, -0.142, 2.081]} scale={0.004} />
      <mesh geometry={nodes.Group_146.geometry} material={materials.Color_A05} position={[8.184, 0.889, -4.851]} rotation={[1.867, -0.563, 1.783]} scale={0.004} />
      <mesh geometry={nodes.Group_145.geometry} material={materials.Color_A05} position={[8.187, 0.897, -4.836]} rotation={[0.644, -0.485, 1.206]} scale={0.004} />
      <mesh geometry={nodes.Group_144.geometry} material={materials.Color_A05} position={[8.196, 0.913, -4.836]} rotation={[-0.325, -0.006, 1.042]} scale={0.004} />
      <mesh geometry={nodes.Group_143.geometry} material={materials.Color_A05} position={[8.218, 0.965, -4.914]} rotation={[-3.128, -0.144, 1.886]} scale={0.004} />
      <mesh geometry={nodes.Group_142.geometry} material={materials.Color_A05} position={[8.164, 0.859, -4.862]} rotation={[2.471, -0.451, 2.081]} scale={0.004} />
      <mesh geometry={nodes.Group_141.geometry} material={materials.Color_A05} position={[8.145, 0.837, -4.849]} rotation={[1.656, -0.768, 1.689]} scale={0.004} />
      <mesh geometry={nodes.Group_140.geometry} material={materials.Color_A05} position={[8.133, 0.83, -4.82]} rotation={[0.656, -0.705, 1.084]} scale={0.004} />
      <mesh geometry={nodes.Group_139.geometry} material={materials.Color_A05} position={[8.135, 0.842, -4.79]} rotation={[-0.07, -0.324, 0.806]} scale={0.004} />
      <mesh geometry={nodes.Group_138.geometry} material={materials.Color_A05} position={[8.15, 0.866, -4.775]} rotation={[-0.652, 0.124, 0.843]} scale={0.004} />
      <mesh geometry={nodes.Group_137.geometry} material={materials.Color_A05} position={[8.192, 0.916, -4.815]} rotation={[-0.585, 0.06, 1.041]} scale={0.004} />
      <mesh geometry={nodes.Group_136.geometry} material={materials.Color_A05} position={[8.174, 0.876, -4.866]} rotation={[0.539, -0.441, 1.061]} scale={0.004} />
      <mesh geometry={nodes.Group_135.geometry} material={materials.Color_A05} position={[8.17, 0.89, -4.782]} rotation={[-1.329, 0.467, 1.149]} scale={0.004} />
      <mesh geometry={nodes.Group_134.geometry} material={materials.Color_A05} position={[8.191, 1.06, -4.694]} rotation={[-2.145, 0.328, 1.158]} scale={0.004} />
      <mesh geometry={nodes.Group_133.geometry} material={materials.Color_A05} position={[8.241, 1.122, -4.866]} rotation={[-3.001, -0.009, 1.453]} scale={0.004} />
      <mesh geometry={nodes.Group_132.geometry} material={materials.Color_A05} position={[8.208, 1.038, -5.033]} rotation={[2.462, -0.451, 1.398]} scale={0.004} />
      <mesh geometry={nodes.Group_131.geometry} material={materials.Color_A05} position={[8.117, 0.875, -5.063]} rotation={[1.405, -0.673, 0.94]} scale={0.004} />
      <mesh geometry={nodes.Group_130.geometry} material={materials.Color_A05} position={[8.041, 0.76, -4.935]} rotation={[0.356, -0.439, 0.491]} scale={0.004} />
      <mesh geometry={nodes.Group_129.geometry} material={materials.Color_A05} position={[8.188, 0.9, -4.826]} rotation={[-2.586, 0.389, 1.899]} scale={0.004} />
      <mesh geometry={nodes.Group_128.geometry} material={materials.Color_A05} position={[8.111, 0.926, -4.647]} rotation={[-1.322, 0.334, 0.752]} scale={0.004} />
      <mesh geometry={nodes.Group_127.geometry} material={materials.Color_A05} position={[8.035, 0.908, -4.601]} rotation={[-1.317, 0.476, 0.53]} scale={0.004} />
      <mesh geometry={nodes.Group_126.geometry} material={materials.Color_A05} position={[8.188, 1.161, -4.704]} rotation={[-2.654, 0.323, 1.139]} scale={0.004} />
      <mesh geometry={nodes.Group_125.geometry} material={materials.Color_A05} position={[8.211, 1.153, -5.016]} rotation={[2.535, -0.253, 1.195]} scale={0.004} />
      <mesh geometry={nodes.Group_124.geometry} material={materials.Color_A05} position={[8.038, 0.783, -4.747]} rotation={[-0.462, 0.004, 0.448]} scale={0.004} />
      <mesh geometry={nodes.Group_123.geometry} material={materials.Color_A05} position={[8.074, 0.893, -5.126]} rotation={[1.225, -0.521, 0.637]} scale={0.004} />
      <mesh geometry={nodes.Group_122.geometry} material={materials.Color_A05} position={[7.957, 0.725, -4.889]} rotation={[0, -0.098, 0.216]} scale={0.004} />
      <mesh geometry={nodes.Group_120.geometry} material={materials.Color_G16} position={[7.94, 0.739, -4.836]} rotation={[0, -0.098, 0.216]} scale={0.004} />
      <mesh geometry={nodes.Group_119.geometry} material={materials.Color_A05} position={[8.201, 0.919, -4.852]} rotation={[-1.315, 0.396, 1.353]} scale={0.004} />
      <mesh geometry={nodes.Group_117.geometry} material={materials.Color_A05} position={[8.15, 0.849, -4.996]} rotation={[0.814, -0.204, 0.519]} scale={0.004} />
      <mesh geometry={nodes.Group_116.geometry} material={materials.Color_A05} position={[8.131, 0.908, -5.06]} rotation={[0.532, 0.653, 0.634]} scale={0.004} />
      <mesh geometry={nodes.Group_115.geometry} material={materials.Color_A05} position={[8.054, 0.921, -5.102]} rotation={[-0.847, 1.254, 1.905]} scale={0.004} />
      <mesh geometry={nodes.Group_114.geometry} material={materials.Color_A05} position={[7.977, 0.878, -5.09]} rotation={[-2.084, 0.605, 3.032]} scale={0.004} />
      <mesh geometry={nodes.Group_113.geometry} material={materials.Color_A05} position={[7.958, 0.812, -5.034]} rotation={[-2.357, -0.253, 3.13]} scale={0.004} />
      <mesh geometry={nodes.Group_112.geometry} material={materials.Color_A05} position={[8.012, 0.772, -4.975]} rotation={[-2.784, -1.098, 2.879]} scale={0.004} />
      <mesh geometry={nodes.Group_111.geometry} material={materials.Color_A05} position={[8.083, 0.899, -5.075]} rotation={[-2.1, -0.052, 2.78]} scale={0.004} />
      <mesh geometry={nodes.Group_110.geometry} material={materials.Color_A05} position={[7.987, 0.841, -5.057]} rotation={[0.826, -0.513, 0.033]} scale={0.004} />
      <mesh geometry={nodes.Group_109.geometry} material={materials.Color_A05} position={[8.045, 0.844, -5.05]} rotation={[-2.417, -0.599, 2.862]} scale={0.004} />
      <mesh geometry={nodes.Group_108.geometry} material={materials.Color_A05} position={[8.042, 0.831, -5.039]} rotation={[1.988, -1.373, 1.183]} scale={0.004} />
      <mesh geometry={nodes.Group_107.geometry} material={materials.Color_A05} position={[8.055, 0.825, -5.028]} rotation={[0.843, -0.455, 0.246]} scale={0.004} />
      <mesh geometry={nodes.Group_106.geometry} material={materials.Color_A05} position={[8.071, 0.832, -5.029]} rotation={[0.532, 0.545, 0.36]} scale={0.004} />
      <mesh geometry={nodes.Group_105.geometry} material={materials.Color_A05} position={[8.074, 0.846, -5.041]} rotation={[-0.977, 1.209, 1.764]} scale={0.004} />
      <mesh geometry={nodes.Group_104.geometry} material={materials.Color_A05} position={[8.009, 0.894, -5.093]} rotation={[-2.695, -1.421, 2.536]} scale={0.004} />
      <mesh geometry={nodes.Group_103.geometry} material={materials.Color_A05} position={[8.036, 0.801, -5.007]} rotation={[0.923, -0.989, 0.299]} scale={0.004} />
      <mesh geometry={nodes.Group_102.geometry} material={materials.Color_A05} position={[8.042, 0.783, -4.981]} rotation={[0.613, -0.299, 0.198]} scale={0.004} />
      <mesh geometry={nodes.Group_101.geometry} material={materials.Color_A05} position={[8.066, 0.778, -4.961]} rotation={[0.362, 0.386, 0.308]} scale={0.004} />
      <mesh geometry={nodes.Group_100.geometry} material={materials.Color_A05} position={[8.097, 0.788, -4.957]} rotation={[-0.205, 0.984, 0.788]} scale={0.004} />
      <mesh geometry={nodes.Group_099.geometry} material={materials.Color_A05} position={[8.117, 0.808, -4.972]} rotation={[-1.614, 0.994, 2.121]} scale={0.004} />
      <mesh geometry={nodes.Group_098.geometry} material={materials.Color_A05} position={[8.093, 0.849, -5.031]} rotation={[-1.457, 1.034, 2.192]} scale={0.004} />
      <mesh geometry={nodes.Group_097.geometry} material={materials.Color_A05} position={[8.037, 0.815, -5.021]} rotation={[0.493, 0.644, 0.284]} scale={0.004} />
      <mesh geometry={nodes.Group_096.geometry} material={materials.Color_A05} position={[8.117, 0.828, -4.997]} rotation={[-2.197, 0.401, 2.617]} scale={0.004} />
      <mesh geometry={nodes.Group_095.geometry} material={materials.Color_A05} position={[8.22, 0.988, -5.027]} rotation={[-2.268, -0.357, 2.296]} scale={0.004} />
      <mesh geometry={nodes.Group_094.geometry} material={materials.Color_A05} position={[8.073, 1.041, -5.133]} rotation={[-2.633, -1.236, 2.155]} scale={0.004} />
      <mesh geometry={nodes.Group_093.geometry} material={materials.Color_A05} position={[7.898, 0.97, -5.13]} rotation={[0.926, -0.981, -0.379]} scale={0.004} />
      <mesh geometry={nodes.Group_092.geometry} material={materials.Color_A05} position={[7.832, 0.831, -5.021]} rotation={[0.676, -0.097, -0.373]} scale={0.004} />
      <mesh geometry={nodes.Group_091.geometry} material={materials.Color_A05} position={[7.927, 0.732, -4.891]} rotation={[0.327, 0.75, -0.101]} scale={0.004} />
      <mesh geometry={nodes.Group_090.geometry} material={materials.Color_A05} position={[8.081, 0.835, -5.027]} rotation={[-2.588, -0.669, 2.719]} scale={0.004} />
      <mesh geometry={nodes.Group_089.geometry} material={materials.Color_A05} position={[8.235, 0.873, -4.912]} rotation={[-2.053, 0.39, 2.167]} scale={0.004} />
      <mesh geometry={nodes.Group_088.geometry} material={materials.Color_A05} position={[8.259, 0.87, -4.825]} rotation={[-2.206, 0.412, 2.008]} scale={0.004} />
      <mesh geometry={nodes.Group_087.geometry} material={materials.Color_A05} position={[8.219, 1.087, -5.047]} rotation={[-2.583, -0.76, 1.939]} scale={0.004} />
      <mesh geometry={nodes.Group_086.geometry} material={materials.Color_A05} position={[7.923, 1.081, -5.152]} rotation={[1.297, -1.063, -0.289]} scale={0.004} />
      <mesh geometry={nodes.Group_085.geometry} material={materials.Color_A05} position={[8.108, 0.751, -4.842]} rotation={[-1.226, 1.114, 1.399]} scale={0.004} />
      <mesh geometry={nodes.Group_084.geometry} material={materials.Color_A05} position={[7.762, 0.859, -5]} rotation={[0.775, 0.09, -0.574]} scale={0.004} />
      <mesh geometry={nodes.Group_083.geometry} material={materials.Color_A05} position={[7.947, 0.714, -4.793]} rotation={[0, 1.201, 0]} scale={0.004} />
      <mesh geometry={nodes.Group_081.geometry} material={materials.Color_G16} position={[7.994, 0.731, -4.765]} rotation={[0, 1.201, 0]} scale={0.004} />
      <mesh geometry={nodes.Group_080.geometry} material={materials.Color_A05} position={[8.061, 0.851, -5.051]} rotation={[-2.119, 0.405, 2.796]} scale={0.004} />
      <mesh geometry={nodes.Group_078.geometry} material={materials.Color_A05} position={[8.079, 0.784, -5.039]} rotation={[0.715, 0.079, 0.232]} scale={0.004} />
      <mesh geometry={nodes.Group_077.geometry} material={materials.Color_A05} position={[8.036, 0.839, -5.095]} rotation={[0.715, 0.975, 0.276]} scale={0.004} />
      <mesh geometry={nodes.Group_076.geometry} material={materials.Color_A05} position={[7.949, 0.851, -5.104]} rotation={[-2.31, 1.268, -2.949]} scale={0.004} />
      <mesh geometry={nodes.Group_075.geometry} material={materials.Color_A05} position={[7.883, 0.811, -5.06]} rotation={[-2.342, 0.372, -2.877]} scale={0.004} />
      <mesh geometry={nodes.Group_074.geometry} material={materials.Color_A05} position={[7.888, 0.75, -4.996]} rotation={[-2.313, -0.524, -2.83]} scale={0.004} />
      <mesh geometry={nodes.Group_073.geometry} material={materials.Color_A05} position={[7.96, 0.713, -4.96]} rotation={[-1.923, -1.407, -2.43]} scale={0.004} />
      <mesh geometry={nodes.Group_072.geometry} material={materials.Color_A05} position={[7.986, 0.83, -5.09]} rotation={[-2.127, -0.25, 3.134]} scale={0.004} />
      <mesh geometry={nodes.Group_071.geometry} material={materials.Color_A05} position={[7.905, 0.777, -5.031]} rotation={[0.637, -0.22, -0.264]} scale={0.004} />
      <mesh geometry={nodes.Group_070.geometry} material={materials.Color_A05} position={[7.961, 0.778, -5.048]} rotation={[-2.219, -0.867, -3.012]} scale={0.004} />
      <mesh geometry={nodes.Group_069.geometry} material={materials.Color_A05} position={[7.963, 0.766, -5.035]} rotation={[0.451, -1.203, -0.311]} scale={0.004} />
      <mesh geometry={nodes.Group_068.geometry} material={materials.Color_A05} position={[7.979, 0.761, -5.03]} rotation={[0.669, -0.169, -0.053]} scale={0.004} />
      <mesh geometry={nodes.Group_067.geometry} material={materials.Color_A05} position={[7.993, 0.767, -5.038]} rotation={[0.658, 0.874, 0.049]} scale={0.004} />
      <mesh geometry={nodes.Group_066.geometry} material={materials.Color_A05} position={[7.991, 0.78, -5.05]} rotation={[-2.207, 1.215, 2.974]} scale={0.004} />
      <mesh geometry={nodes.Group_065.geometry} material={materials.Color_A05} position={[7.911, 0.825, -5.077]} rotation={[-0.311, -1.297, -1.269]} scale={0.004} />
      <mesh geometry={nodes.Group_064.geometry} material={materials.Color_A05} position={[7.97, 0.739, -5.001]} rotation={[0.528, -0.692, -0.116]} scale={0.004} />
      <mesh geometry={nodes.Group_063.geometry} material={materials.Color_A05} position={[7.986, 0.723, -4.978]} rotation={[0.502, 0.036, -0.027]} scale={0.004} />
      <mesh geometry={nodes.Group_062.geometry} material={materials.Color_A05} position={[8.016, 0.719, -4.969]} rotation={[0.385, 0.757, 0.12]} scale={0.004} />
      <mesh geometry={nodes.Group_061.geometry} material={materials.Color_A05} position={[8.046, 0.728, -4.978]} rotation={[-0.668, 1.361, 1.194]} scale={0.004} />
      <mesh geometry={nodes.Group_060.geometry} material={materials.Color_A05} position={[8.059, 0.746, -5.001]} rotation={[-2.22, 0.864, 2.767]} scale={0.004} />
      <mesh geometry={nodes.Group_059.geometry} material={materials.Color_A05} position={[8.013, 0.783, -5.05]} rotation={[-2.157, 0.948, 2.922]} scale={0.004} />
      <mesh geometry={nodes.Group_058.geometry} material={materials.Color_A05} position={[7.965, 0.752, -5.015]} rotation={[0.659, 0.978, -0.049]} scale={0.004} />
      <mesh geometry={nodes.Group_057.geometry} material={materials.Color_A05} position={[8.049, 0.764, -5.026]} rotation={[-2.367, 0.146, 2.942]} scale={0.004} />
      <mesh geometry={nodes.Group_056.geometry} material={materials.Color_A05} position={[8.131, 0.918, -5.107]} rotation={[-2.178, -0.593, 2.664]} scale={0.004} />
      <mesh geometry={nodes.Group_055.geometry} material={materials.Color_A05} position={[7.954, 0.968, -5.15]} rotation={[-1.059, -1.38, -2.442]} scale={0.004} />
      <mesh geometry={nodes.Group_054.geometry} material={materials.Color_A05} position={[7.794, 0.902, -5.073]} rotation={[0.534, -0.685, -0.792]} scale={0.004} />
      <mesh geometry={nodes.Group_053.geometry} material={materials.Color_A05} position={[7.777, 0.773, -4.936]} rotation={[0.611, 0.218, -0.624]} scale={0.004} />
      <mesh geometry={nodes.Group_052.geometry} material={materials.Color_A05} position={[7.915, 0.681, -4.846]} rotation={[0.481, 1.118, -0.386]} scale={0.004} />
      <mesh geometry={nodes.Group_051.geometry} material={materials.Color_A05} position={[8.003, 0.77, -5.04]} rotation={[-2.387, -0.985, 3.096]} scale={0.004} />
      <mesh geometry={nodes.Group_050.geometry} material={materials.Color_A05} position={[8.19, 0.812, -4.997]} rotation={[-2.236, 0.181, 2.526]} scale={0.004} />
      <mesh geometry={nodes.Group_049.geometry} material={materials.Color_A05} position={[8.246, 0.815, -4.926]} rotation={[-2.379, 0.155, 2.33]} scale={0.004} />
      <mesh geometry={nodes.Group_048.geometry} material={materials.Color_A05} position={[8.122, 1.016, -5.132]} rotation={[-2.31, -1.067, 2.378]} scale={0.004} />
      <mesh geometry={nodes.Group_047.geometry} material={materials.Color_A05} position={[7.809, 1.01, -5.112]} rotation={[0.713, -0.85, -0.895]} scale={0.004} />
      <mesh geometry={nodes.Group_046.geometry} material={materials.Color_A05} position={[8.102, 0.699, -4.874]} rotation={[-2.124, 1.082, 2.305]} scale={0.004} />
      <mesh geometry={nodes.Group_045.geometry} material={materials.Color_A05} position={[7.72, 0.805, -4.892]} rotation={[0.763, 0.372, -0.87]} scale={0.004} />
      <mesh geometry={nodes.Group_044.geometry} material={materials.Color_A05} position={[7.972, 0.671, -4.763]} rotation={[-Math.PI, 1.538, 3.061]} scale={0.004} />
      <mesh geometry={nodes.Group_042.geometry} material={materials.Color_G16} position={[8.026, 0.689, -4.757]} rotation={[-Math.PI, 1.538, 3.061]} scale={0.004} />
      <mesh geometry={nodes.Group_041.geometry} material={materials.Color_A05} position={[7.975, 0.785, -5.055]} rotation={[-2.3, 0.174, 3.141]} scale={0.004} />
      <mesh geometry={nodes.Group_039.geometry} material={materials.Color_A05} position={[8.131, 0.784, -4.688]} rotation={[1.912, -0.804, 2.329]} scale={0.004} />
      <mesh geometry={nodes.Group_038.geometry} material={materials.Color_A05} position={[8.199, 0.839, -4.705]} rotation={[0.56, -0.807, 1.325]} scale={0.004} />
      <mesh geometry={nodes.Group_037.geometry} material={materials.Color_A05} position={[8.243, 0.851, -4.781]} rotation={[-0.227, -0.204, 0.955]} scale={0.004} />
      <mesh geometry={nodes.Group_036.geometry} material={materials.Color_A05} position={[8.229, 0.811, -4.859]} rotation={[-0.843, 0.464, 1.087]} scale={0.004} />
      <mesh geometry={nodes.Group_035.geometry} material={materials.Color_A05} position={[8.168, 0.75, -4.881]} rotation={[-1.905, 0.83, 1.822]} scale={0.004} />
      <mesh geometry={nodes.Group_034.geometry} material={materials.Color_A05} position={[8.106, 0.713, -4.829]} rotation={[-2.97, 0.467, 2.561]} scale={0.004} />
      <mesh geometry={nodes.Group_033.geometry} material={materials.Color_A05} position={[8.214, 0.83, -4.753]} rotation={[-1.595, 0.604, 1.226]} scale={0.004} />
      <mesh geometry={nodes.Group_032.geometry} material={materials.Color_A05} position={[8.194, 0.777, -4.851]} rotation={[2.299, -0.681, 2.102]} scale={0.004} />
      <mesh geometry={nodes.Group_031.geometry} material={materials.Color_A05} position={[8.186, 0.778, -4.793]} rotation={[-2.378, 0.728, 1.915]} scale={0.004} />
      <mesh geometry={nodes.Group_030.geometry} material={materials.Color_A05} position={[8.174, 0.766, -4.797]} rotation={[2.984, 0.081, 2.42]} scale={0.004} />
      <mesh geometry={nodes.Group_029.geometry} material={materials.Color_A05} position={[8.163, 0.761, -4.784]} rotation={[2.223, -0.694, 2.259]} scale={0.004} />
      <mesh geometry={nodes.Group_028.geometry} material={materials.Color_A05} position={[8.164, 0.767, -4.768]} rotation={[0.67, -0.886, 1.134]} scale={0.004} />
      <mesh geometry={nodes.Group_027.geometry} material={materials.Color_A05} position={[8.176, 0.78, -4.764]} rotation={[-0.289, -0.191, 0.679]} scale={0.004} />
      <mesh geometry={nodes.Group_026.geometry} material={materials.Color_A05} position={[8.233, 0.825, -4.827]} rotation={[-3.058, 0.154, 2.16]} scale={0.004} />
      <mesh geometry={nodes.Group_025.geometry} material={materials.Color_A05} position={[8.14, 0.739, -4.803]} rotation={[2.714, -0.358, 2.511]} scale={0.004} />
      <mesh geometry={nodes.Group_024.geometry} material={materials.Color_A05} position={[8.112, 0.723, -4.798]} rotation={[2.159, -0.954, 2.25]} scale={0.004} />
      <mesh geometry={nodes.Group_023.geometry} material={materials.Color_A05} position={[8.091, 0.719, -4.774]} rotation={[0.655, -1.106, 0.993]} scale={0.004} />
      <mesh geometry={nodes.Group_022.geometry} material={materials.Color_A05} position={[8.088, 0.728, -4.744]} rotation={[-0.154, -0.576, 0.453]} scale={0.004} />
      <mesh geometry={nodes.Group_021.geometry} material={materials.Color_A05} position={[8.104, 0.746, -4.723]} rotation={[-0.545, 0.051, 0.443]} scale={0.004} />
      <mesh geometry={nodes.Group_020.geometry} material={materials.Color_A05} position={[8.167, 0.783, -4.744]} rotation={[-0.508, -0.033, 0.647]} scale={0.004} />
      <mesh geometry={nodes.Group_019.geometry} material={materials.Color_A05} position={[8.155, 0.752, -4.802]} rotation={[0.533, -0.832, 0.933]} scale={0.004} />
      <mesh geometry={nodes.Group_018.geometry} material={materials.Color_A05} position={[8.131, 0.764, -4.722]} rotation={[-1.026, 0.628, 0.712]} scale={0.004} />
      <mesh geometry={nodes.Group_017.geometry} material={materials.Color_A05} position={[8.171, 0.918, -4.613]} rotation={[-2.01, 0.719, 1.035]} scale={0.004} />
      <mesh geometry={nodes.Group_016.geometry} material={materials.Color_A05} position={[8.283, 0.968, -4.758]} rotation={[-2.967, 0.317, 1.696]} scale={0.004} />
      <mesh geometry={nodes.Group_015.geometry} material={materials.Color_A05} position={[8.277, 0.902, -4.935]} rotation={[2.706, -0.362, 1.829]} scale={0.004} />
      <mesh geometry={nodes.Group_014.geometry} material={materials.Color_A05} position={[8.159, 0.773, -5.007]} rotation={[1.792, -0.959, 1.365]} scale={0.004} />
      <mesh geometry={nodes.Group_013.geometry} material={materials.Color_A05} position={[8.02, 0.681, -4.916]} rotation={[0.295, -0.801, 0.267]} scale={0.004} />
      <mesh geometry={nodes.Group_012.geometry} material={materials.Color_A05} position={[8.162, 0.77, -4.758]} rotation={[-2.578, 0.783, 2.012]} scale={0.004} />
      <mesh geometry={nodes.Group_011.geometry} material={materials.Color_A05} position={[8.047, 0.812, -4.604]} rotation={[-1.083, 0.504, 0.349]} scale={0.004} />
      <mesh geometry={nodes.Group_010.geometry} material={materials.Color_A05} position={[7.96, 0.815, -4.581]} rotation={[-1.009, 0.632, 0.089]} scale={0.004} />
      <mesh geometry={nodes.Group_009.geometry} material={materials.Color_A05} position={[8.198, 1.016, -4.612]} rotation={[-2.652, 0.71, 1.279]} scale={0.004} />
      <mesh geometry={nodes.Group_008.geometry} material={materials.Color_A05} position={[8.306, 1.01, -4.906]} rotation={[2.689, -0.153, 1.596]} scale={0.004} />
      <mesh geometry={nodes.Group_007.geometry} material={materials.Color_A05} position={[7.97, 0.699, -4.735]} rotation={[-0.415, -0.132, 0.066]} scale={0.004} />
      <mesh geometry={nodes.Group_006.geometry} material={materials.Color_A05} position={[8.141, 0.805, -5.076]} rotation={[1.478, -0.867, 0.914]} scale={0.004} />
      <mesh geometry={nodes.Group_005.geometry} material={materials.Color_A05} position={[7.921, 0.671, -4.898]} rotation={[0, -0.384, -0.08]} scale={0.004} />
      <mesh geometry={nodes.Group_003.geometry} material={materials.Color_G16} position={[7.894, 0.689, -4.851]} rotation={[0, -0.384, -0.08]} scale={0.004} />
      <mesh geometry={nodes.Group_002.geometry} material={materials.Color_A05} position={[8.187, 0.785, -4.777]} rotation={[-1.048, 0.559, 0.934]} scale={0.004} />
      <group position={[7.991, 0.628, -4.847]} rotation={[-Math.PI, 1.09, -Math.PI]} scale={0.004}>
        <mesh geometry={nodes.Mesh207.geometry} material={materials.Material3} />
        <mesh geometry={nodes.Mesh207_1.geometry} material={materials.Material4} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Golden Teak Wood Texture.001']} position={[5.322, 1.6, 0.29]} scale={[2.55, 0.015, 0.3]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Golden Teak Wood Texture.001']} position={[5.322, 1.2, 0.29]} scale={[2.55, 0.015, 0.3]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Golden Teak Wood Texture.001']} position={[5.322, 0.8, 0.29]} scale={[2.55, 0.015, 0.3]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Golden Teak Wood Texture.001']} position={[5.322, 0.4, 0.29]} scale={[2.55, 0.015, 0.3]} />
    </group>
  )
}

useGLTF.preload('/cabine.glb')
